### ISSUE TITLE
Register.php is broken

### ISSUE THREAD

**Issue by eg-be** [eg-be/ybforum#59]
Opps:

`Fatal error: Uncaught Error: Typed property CaptchaVerifier::$m_m_clientIp must not be accessed before initialization in /srv/www/vhosts/1898.ch/httpdocs/helpers/CaptchaVerifier.php:84 Stack trace: #0 /srv/www/vhosts/1898.ch/httpdocs/handlers/RegisterUserHandler.php(97): CaptchaVerifier->VerifyResponse() #1 /srv/www/vhosts/1898.ch/httpdocs/handlers/BaseHandler.php(312): RegisterUserHandler->ValidateParams() #2 /srv/www/vhosts/1898.ch/httpdocs/register.php(44): BaseHandler->HandleRequest() #3 {main} thrown in /srv/www/vhosts/1898.ch/httpdocs/helpers/CaptchaVerifier.php on line 84`

 (where are the unit-tests for the handlers..)

**Comment by eg-be** [comment]
more errors:

`Fatal error: Uncaught TypeError: Return value of ForumDb::IsEmailOnBlacklistExactly() must be an instance of mixed, bool returned in /srv/www/vhosts/1898.ch/httpdocs/model/ForumDb.php:1363 Stack trace: #0 /srv/www/vhosts/1898.ch/httpdocs/handlers/BaseHandler.php(142): ForumDb->IsEmailOnBlacklistExactly() #1 /srv/www/vhosts/1898.ch/httpdocs/handlers/RegisterUserHandler.php(121): BaseHandler->ValidateEmailAgainstBlacklist() #2 /srv/www/vhosts/1898.ch/httpdocs/handlers/BaseHandler.php(315): RegisterUserHandler->HandleRequestImpl() #3 /srv/www/vhosts/1898.ch/httpdocs/register.php(44): BaseHandler->HandleRequest() #4 {main} thrown in /srv/www/vhosts/1898.ch/httpdocs/model/ForumDb.php on line 1363`
